* Forrest Valkai -- Sex and Sensibility

- extraordinary!
- also, long and detailed!

- YouTube Link :: [[https://youtu.be/nVQplt7Chos?si=adfWny1_eMU42yMV][Sex and Sensibility]]

** Overview

Forrest is a biologist and a science communicator who specializes in evolutionary biology, bioanthropology, and biomedical sciences.

Find a text version of my reference list here: https://docs.google.com/document/d/1z...

- 0:00 – Introduction
- 1:52 – Part 1: Understanding Biological Sex
- 7:54 – Diversity in Sex Determination
- 13:29 – Diversity in Sexes
- 19:33 – Part 2: The Spectrum of Sex
- 21:47 – Chromosomal Sex
- 28:04 – Genetic/Gonadal Sex
- 31:23 – Hormones and Anatomical Sex
- 39:51 – Intersex
- 42:23 – Biological Thinking
- 45:51 – Part 3: Gender and Sexuality
- 48:32 – Comparing Social Constructs
- 50:41 – Gender Diversity
- 58:15 – Sex vs. Gender in Nature
- 1:00:10 – Sexuality
- 1:03:10 – Dangerous Pseudoscience
- 1:06:40 – Self-Identification
- 1:10:52 – Neuroscience
- 1:19:57 – Part 4: From Science to Society
- 1:20:17 – Gender and Health
- 1:28:38 – Gender and Science
- 1:31:24 – Summary
- 1:36:10 – References
- 1:38:40 - Conclusion

** Transcript

*** Introduction
- 0:00
- oh hi there I wasn't actually reading this my name is Forest valky and I'm a biologist who teaches here at the prestigious University of on the
- 0:07
- internet about 3 years ago I released a video on why sex and gender are different things and why neither one of
- 0:12
- them is a binary unfortunately as this was my very first video essay it was riddled with poor editing and Loud table
- 0:19
- thumping and I left out a lot of cool details and responses to Common counter arguments that I would normally include
- 0:24
- in a video now so today I've decided to remake that video with more detailed information New Concepts and more than
- 0:30
- one looping background track in this video we're going to cover a wide range of topics and talk about a lot of
- 0:36
- different species this is because the concept of biological sex is usually taught to new Learners in a grossly
- 0:42
- oversimplified way for the sake of brevity and absorption now this is no different than the way that almost any
- 0:48
- Topic in biology is taught at an introductory level but in this case more than most that simplism can lead people
- 0:53
- to make unfair judgments about other people who fall outside of the watered down binary model in their heads if if
- 1:00
- we want to understand sex and gender in a real and meaningful way we're going to need to turn over a few more Stones than
- 1:05
- just a couple of clinical studies in humans so expect to hear a lot of information over the course of this
- 1:10
- video and don't hesitate to pause walk away and come back for more when you're ready in this video we'll learn about
- 1:16
- the concept of sex from a broad lens sexual development in humans why sex is a spectrum rather than a binary the
- 1:23
- concept of gender why self-identification is a necessary part of gender identity a little bit about
- 1:29
- sexuality and most importantly what all this stuff actually means in the real world why you should care and how to
- 1:36
- handle this information going forward so settle in and get ready to learn some biology as we dissect the science of sex
- 1:42
- gender and why life is so much more interesting than you might have

*** Part 1: Understanding Biological Sex
- 1:56
- thought let's start with the basics human are animals we are living things
- 2:02
- and we are not plants or fungi or protus or bacteria or archa we are simply
- 2:08
- animals and we obey the same laws of nature as every other animal I'm mentioning this right at the outset
- 2:14
- because it's shockingly controversial among new Learners lots of people think that humans are somehow inherently
- 2:19
- special and that we have some privileged place in the world that makes us separate from all other life we're not
- 2:26
- and we don't cells are the most fundamental units of Life they are the smallest things that we can call alive
- 2:32
- and every living thing is made up of at least one cell your body is made up of tens of trillions of cells of all shapes
- 2:38
- and sizes and they do all manner of different things cells make tissues tissues make organs organs make organ
- 2:46
- systems and organ systems make organisms like you and me almost every single cell in your body contains DNA or deoxy
- 2:54
- ribonucleic acid DNA is sort of like an instruction manual that your body uses to do most things Main mainly making
- 3:00
- proteins a long stretch of DNA that codes for one particular thing is called a gene a massive stretch of DNA
- 3:06
- containing lots and lots of genes can be tightly wound around proteins called histones to form a thick rope called
- 3:12
- chromatin which is then further coiled and compacted to form a chromosome most humans have 46 chromosomes that are
- 3:19
- broken up into 23 pairs usually with one of each pair coming from each parent the
- 3:24
- last pair of chromosomes are called alomes or more commonly sex chromosomes which differentiates them from the other
- 3:30
- 44 chromosomes which we call autosomes the full complement of genetic material that an organism contains is called its
- 3:37
- genotype however it's important to remember that just because an organism has certain genes within its genotype
- 3:43
- that doesn't mean that all of those genes are going to be expressed in the same way or at the same time or in all
- 3:49
- cells or even at all the actual observed characteristics of an organism whatever
- 3:54
- its genotype may be are collectively called its phenotype lots of species have different sexual phenotypes for
- 4:01
- males and females a condition that we call dimorphism from the word die meaning two and morph meaning shape and
- 4:08
- dimorphism can occur in varying degrees from species to species the term for a species having separate males and
- 4:14
- females in the first place is called being dous which means two houses and that's what separates those species from
- 4:20
- the monious or one house species other words for monious and dous are hermaphroditic and goric although
- 4:27
- depending on where you're from those words may be more or less common in my training I heard the words hermaphroditic and dous way more than
- 4:34
- the words monious or goric and I have plenty of friends with the exact opposite experience that sort of thing
- 4:40
- is very common in biology and now that we know a little bit about the associated terminology let's talk about
- 4:45
- what biological sex actually is in biology sex is not just a term for the act of reproduction through the
- 4:52
- reassortment of genes and the blending of genomes it's also the way that we categorize individuals of a sexually
- 4:57
- reproducing species to make distinction clear over the course of this video I'll be sure to use the term sexual
- 5:03
- reproduction to refer to the formation of genetically distinct Offspring and the term sex to refer to the sexual
- 5:08
- phenotype of individual organisms sex is a complex thing with a number of different factors going into it that
- 5:14
- we'll cover over the course of this video but in the world of biology the most common way to differentiate between
- 5:19
- the Sexes of an individual species is by looking at the size of their germ cells otherwise known as the reproductive
- 5:25
- cells or more commonly their gametes if you have lots and lots of very small
- 5:30
- mobile gametes we call those sperm and we call you a male if however you have relatively few very large and immobile
- 5:37
- gamet we call those eggs and we call you a female now right away you can notice there's a pretty big problem here what
- 5:43
- if you don't have any gamits what if you haven't started producing yet what if you're infertile surely that doesn't
- 5:48
- mean that you just don't have a sex right the thing that you have to understand about science especially
- 5:54
- biology is that nature is what nature is it has no definitions and very few clear
- 6:00
- boundaries so one of the ways that scientists are able to organize information and make analyses is by
- 6:06
- looking for patterns out in nature and drawing Little Boxes around them but that doesn't necessarily mean that the
- 6:11
- boxes or even the patterns are actually real consider for example the concept of
- 6:17
- species understanding what a species is and where one species starts and another begins is really important in biology
- 6:24
- but there is no definition for the word species nor is there any concrete way to say what a species is and isn't we have
- 6:32
- several species Concepts but they all have their own flaws and there isn't a single one of them that's universally
- 6:38
- applicable and the same sort of thing is true for other big Concepts in biology like homology or novelty these are
- 6:43
- things that have different meanings for different subdisciplines of biology in different circumstances and sometimes
- 6:48
- just in different contexts but we're still able to work with these Concepts despite the fact that we don't have a single operational and Universal
- 6:56
- definition for them the point is sex is not unique here like makes all the rules and breaks all the rules all the time
- 7:02
- and no matter what we're talking about in biology there's almost always some wiggle room and some gray area and the
- 7:08
- fact that I have to explain that at the beginning of this video should give you a pretty good indication as to how the rest of it's going to go ignoring the
- 7:15
- fact that an individual of a disa species may not have any gametes at all the generalization of sex as a function
- 7:21
- of gamet size simply doesn't work on a broad scale any more than any single concept of species does which is why
- 7:27
- when we talk about sex we usually break it down into several subcategories we could be talking about anatomical sex or
- 7:33
- phenotypic sex or chromosomal sex or genetic sex or hormonal sex or gonadal sex or we could be lumping several of
- 7:40
- those together into typological boxes for Pure convenience we'll talk more about all of that as we move along but
- 7:46
- right now let's talk about sex determination the mechanisms by which sex is established in the first place
- 7:51
- and take a look at some of the diversity of sex determination throughout nature we'll begin with reptiles which exhibit
- Diversity in Sex Determination
- 7:56
- some of the widest variety of sex chromosome structure and sex determination mechanisms out of all vertebrates lots of species of reptiles
- 8:03
- and also lots of species of fish but we're not talking about that right now have temperature dependent sex determination that means that the
- 8:09
- anatomical sex of the animal is determined by the temperature at which the eggs are incubated at a critical period of embryonic development known as
- 8:16
- the thermosensitive period so for example in leopard geckos if an egg is incubated at 30° C the resulting lizard
- 8:23
- will be female but if it's incubated at 32° C the resulting lizard will be male
- 8:28
- and if it's incubated at 3 4° C it switches back around to female again those are known as hot females and
- 8:34
- they're known to be especially aggressive and I think that's great and of course this isn't a perfect system no matter the temperature the sex of an
- 8:40
- embryo isn't guaranteed one temperature is just more likely to produce a certain sex than another and somewhere in the
- 8:46
- middle you get a temperature where you get more or less a 1:1 ratio and all of these temperatures are different for
- 8:52
- each reptile species that uses this system of The Reptilian species that do rely on sex chromosomes for sex
- 8:57
- determination it's a tossup as as to whether or not the homozygotes the ones with two of the same alome will be the
- 9:03
- males or the females birds for example have Z and W alomes instead of X and Y
- 9:09
- the major difference between the XY and the ZW systems is which sex has homologous or the same kind of alomes so
- 9:16
- in the ZW system those with ZZ alomes are usually male and those with ZW
- 9:21
- alomes are usually female the exact opposite of what you would expect in mammals where XX usually means female
- 9:27
- and XY usually means male and when you remember that birds and mammals share an amniote ancestor this all becomes
- 9:34
- beautifully relevant from an evolutionary perspective I mean we like to pretend that mammals are very cut and dry about all this sex stuff but they
- 9:40
- are super not I mean just think about the fact that platypuses have 10 sex chromosomes 10 many of them share
- 9:47
- homologies with the AV and Z chromosome and none of them have an important Maman sex determining Gene called sry which
- 9:52
- we're going to be talking about later how Wild is that and while we're on the topic of sex chromosomes there are even
- 9:58
- other ways to get genetic sex differences without sex chromosomes at all consider for example ants which use
- 10:04
- a sex determination system called haooy in which any egg which gets fertilized now has two copies of its genome just
- 10:10
- like you do and will automatically develop into a female any egg that is left unfertilized on the other hand will
- 10:16
- automatically develop into a male this system has some really cool implications the first of which being that male ants
- 10:21
- can never have male children because as soon as they fertilize an egg it will develop into a female they can have male
- 10:28
- grandchildren because one of of their female children can lay an egg that goes unfertilized but there is no unbroken
- 10:33
- chain of males in this system at least not in the same way that there is in our system and that brings me to the other
- 10:39
- thing this is a very different sex determination system than the one that we rely on and it occurs in way more
- 10:45
- taxa than just ants but even if we were just talking about ants there are several times more species of ants alone
- 10:54
- than there are species of mammals total and when we factor in all the other things that use that Hao diploidy system
- 11:00
- bees and wasps and a lot of beetles and a lot of arachnids we're talking about millions and millions of species that
- 11:08
- disobey pretty much everything that most people learn about sex in the sixth grade more importantly however we need
- 11:14
- to remember that even this system which sounds at face value to be pretty darn binary there are exceptions sometimes an
- 11:21
- unfertilized egg will still develop into a female and that female can even go on to lay eggs of their own we call this
- 11:27
- parthenogenesis or reproduction without the assistance of a male and there are plenty of other species including lots
- 11:34
- of vertebrate species that can do that there are even some species like the whiptail lizards in the southwestern us
- 11:40
- which are entirely female and only reproduced this way but let's back up a little bit I said at the beginning of
- 11:46
- this section that the most common way to determine sex is through gamit size big means female small means male but even
- 11:52
- that raises a lot of issues first of all the whole idea that being either male or female is a persistent condition which
- 11:59
- is understood from birth is deeply flawed to say the least there are plenty of species out there that are hermaphroditic they make both sperm and
- 12:06
- eggs and there are plenty more species out there which are sequentially or serially hermaphroditic they start off
- 12:12
- as one sex and then at some point in their life they switch if they start off male and then become female later we call that protandry if they start off
- 12:18
- female and then become male later we call that protoy there are other species like the slipper limpets and adorable
- 12:24
- species of sea snails that live in stacks on the ocean floor that are sequentially hermaphroditic but they
- 12:29
- have no guaranteed starting point their sex is determined by where they are on the stack with those on top being male
- 12:36
- and those on bottom being female so even if one of them has been a male for a very long time all it takes is another
- 12:41
- limpic climbing on top and it'll just turn into a female they're also plenty of species like the stoplight parrot
- 12:47
- fish which are sequentially hermaphroditic but don't have to be they only switch Sexes if they can't find a
- 12:53
- mate and there are even other species which are bidirectionally hermaphroditic meaning they can swap back and forth all
- 12:59
- of these situations constitute massive evolutionary advantages because these individuals get to pass their genes
- 13:04
- along regardless of what sex they have to be to do it and the other members of their population get to do the same all
- 13:10
- that is to say sperm versus egg production is not a bad way to talk about sex it's just important to
- 13:15
- remember that it's not always the full story in all those examples I just gave there are species which produce sperm at
- 13:21
- one point in their lives and eggs at another point in their lives meaning their sex is neither fixed nor immutable
- 13:26
- and asking for their sex is about as useful as asking for the time but even with all that in mind we could still say
- Diversity in Sexes
- 13:32
- that these species are producing either one type of gamet or the other or both at any given time and because there are
- 13:38
- still just these two types of gametes this is still ultimately a binary system the problem is that only applies because
- 13:45
- we're talking about an isogamous species here species which have more than one size of gamt and there are plenty of
- 13:51
- species which are isog gamus meaning they have only one size of gamt so what are we supposed to do with them and to
- 13:57
- be clear being isog gamus isn't the same thing as being hermaphroditic these species still differentiate into mating
- 14:03
- types which you can kind of think of as males and females only we would call them plus and minus based on who's giving and who's receiving the gametes
- 14:09
- and of course if we were to try to Define everybody that way then animals like seahorses would have their sexes swapped because the females deposit eggs
- 14:16
- into the males who then fertilize them and give birth to live young and then there's tetrahymena thmil a radical
- 14:22
- little protozoan with seven distinct mating types each one of which can reproduce with any of the other six but
- 14:27
- not with its own there are also some species out there that have more than two gamet sizes for example there's a
- 14:32
- species of fruit fly which has one size of egg and three different sizes of sperm so if size is really all that
- 14:39
- matters we should be saying that there are four Sexes here or at the very least there's two but one of them is broken
- 14:44
- down into three subcategories one of which violates this whole system anyway because its sperm is bigger than the egg
- 14:50
- and that's not even mentioning the situations where the sperm is bigger than the entire fly there's also a genus
- 14:56
- of green algae which can reproduce in a variety of ways some a sexual some sexual and one of the sexual ways that
- 15:01
- it can reproduce is to divide itself up to 64 times until it becomes its own
- 15:07
- gametes each of the daughter cells grows a flagellum and becomes a gamet of a variety of sizes and then there's the
- 15:13
- genus pandina which lives in colonies of 16 cells which then divide into eight large and eight small gametes only any
- 15:20
- of those gametes can fuse two big two small one big one small you name it some plants also have sperm and eggs although
- 15:26
- they do things a little bit differently looking just at the angiosperms the flowering plants they can be either
- 15:31
- monious or dous but even within those two categories there's a lot of variation when a flower has both male
- 15:38
- and female parts we call it a perfect flower apricots are a great example of a Monisha species with perfect flowers
- 15:45
- when a flower has either male or female parts we call those imperfect flowers so you could have a disa species like Aspen
- 15:52
- trees in which each tree is either male or female but you could also have imperfect flowers within a mon species
- 15:59
- walnut trees for example are monious and have both male and female flowers on the
- 16:04
- same tree and then there are fungi which also have different mating types which are sort of analogous to the sexes in
- 16:10
- plants and animals in that they each possess a particular set of genes which conveys a particular sexual phenotype
- 16:15
- the difference is that in some fungi like yeast there are two mating types and in other fungi like split Gill
- 16:21
- mushrooms there are over 23,000 mating types and even among all those mating
- 16:27
- types there are different levels of of complexity with some mating types being unipolar bipolar or tetrapolar depending
- 16:33
- on how many crossover events there are and how many genes are actually being shared during reproduction and none of
- 16:39
- that is even touching on the fact that there are some fungi which are homothallic meaning they can self- fertilize and reproduce from a single
- 16:45
- Spore and then there are heterothallic fungi which need other compatible fungi to reproduce with nor is it touching on
- 16:52
- the fact that some fungi can exist in an anamorphic or asexual form or a tmorph
- 16:58
- or sexual form allowing them to adapt their reproductive strategy to whatever their local environment requires and
- 17:05
- even if you were to really really try to say that all of these fungi actually exist in a very specific discrete sexual
- 17:12
- category the hyi or the roots of the fungus can have multiple nuclei within
- 17:17
- the same cell and those nuclei can contain different genomes of different mating types which means one single
- 17:23
- fungal system can have lots of different Sexes all at once and even if we walk it
- 17:29
- all the way back to strictly dous and anog species there are still individuals
- 17:35
- which we call gynandromorphs which means they have some male and some female parts within the same body there are
- 17:41
- even some of them which we call bilateral gandr morphs because they're split right down the middle with one
- 17:47
- half of their body being male and the other half being female bilateral gandr morphy doesn't really happen in mammals
- 17:53
- but it does happen in Maman gonads ovotestes are organs which have ovarian tissue on one side and testicular tissue
- 18:00
- on the other side that can happen in humans and in many other mammals and there are even some mammals like
- 18:06
- European moles where that is the normal ground state of all females perhaps this is all just a bit too weird and you want
- 18:12
- to try to do away with all this variation and combine sex and sexual reproduction boiling sex down to just
- 18:19
- the function of genome blend unfortunately if you do that things are going to get a whole lot weirder
- 18:24
- consider for example the fact that bacteria can share genes in lots of different ways one of those ways is
- 18:30
- called conjugation which is essentially bacterial mating during conjugation a donor cell connects to a recipient cell
- 18:36
- and gives them plasma genes which they can use the attachment is even done by a structure called a sex pilus how are you
- 18:42
- going to talk about males and females in an organism which has no sex chromosomes no sex organs no gametes no more than
- 18:49
- one cell and in which any individual could give or receive DNA at any given time and let's not forget the fact that
- 18:56
- bacteria can also do this neat trick called trans information where they can incorporate free DNA into their genomes
- 19:02
- and that DNA can be sourced from pretty much anywhere including dead bacteria if
- 19:07
- you really want to say that sex is all just about genome blending then you'd have to admit that sometimes functional
- 19:14
- sexual reproduction can happen with dead things so it's important that we have some sort of structure to this concept
- 19:20
- of sex but as we've just seen that structure is highly variable and can be pretty difficult to pin down so where do
- 19:26
- we go from here well it just so happens that this EX exact issue is why Modern Biology is Shifting to a new model of a
- 19:32
- sex Spectrum let's talk about [Music]

*** Part 2: The Spectrum of Sex
- 19:39
- that for a lot of people the concept of sex being multi-dimensional Dynamic and
- 19:44
- spectral can be a little bit daunting but Spectra in nature even regarding sex
- 19:49
- is something that you're almost certainly already more familiar with than you may realize consider for example human height we know that male
- 19:56
- humans are 10 to 15% taller than female but when we look at how that data plots out the actual distribution of height
- 20:03
- between Sexes we see that there's certainly a difference between averages but the overlap is nearly 2/3 of the
- 20:09
- graph so when we say that males are 10 to 15% taller than females we don't mean that every male is taller than every
- 20:16
- female nor do we mean that height alone is a reliable way to distinguish between Sexes nor do we mean that any male
- 20:23
- that's shorter than an average female isn't actually a male or that there's a height limit to females or anything like
- 20:29
- that we're just talking about a trend in the population and when you start thinking about almost any sex-based
- 20:35
- characteristic even sex determining factors you'll find that we're talking about Trends not binaries a whole heck
- 20:41
- of a lot despite popular belief there is no single simple switch for sex determination in fact the more we've
- 20:48
- looked at it the more we found that sex is a multivariant system a suite of diverse characteristics produced by an
- 20:55
- array of different factors no single one of which is solely determinant of the outcome and no single one of which has
- 21:01
- only two options and to better understand what I mean by that let's look at humans as a case study overall
- 21:06
- there are four major steps to sex determination in humans first is the establishment of your chromosomal sex at
- 21:12
- the time of fertilization this is usually either XX or XY second is the development of gonads due to the
- 21:18
- expression of genetic Pathways encoded on those chromosomes this establishes your gatal sex third is the continuation
- 21:24
- of sex specific development of your internal and external genitalia which is what establishes your anatomical sex and
- 21:31
- finally you establish outwardly visible sex characteristics which is what establishes your phenotypic sex and
- 21:36
- while that all sounds very straightforward at face value when you understand the sheer range of possibilities in each one of those four
- 21:43
- steps you'll start to see why it's completely impossible to call any part of this a binary let's start big with
- Chromosomal Sex
- 21:49
- the idea that XX always means female and XY always means male right away this has
- 21:54
- a lot of problems de Chappelle syndrome is when a person has XX chromosomes but still develops anatomically as a male
- 22:01
- this usually happens because the SR y Gene an important Gene for male development is translocated or moved
- 22:07
- onto an X chromosome but this isn't always the case because the genes for both testes and ovaries are Upstream so
- 22:14
- to speak there are individuals with de Chappelle syndrome who don't possess any y derived genes at all and just as de
- 22:21
- Chappelle syndrome is a variation in the sex characteristics of people with XX chromosomes Swire syndrome is a
- 22:27
- variation in the sex characteristics of people with XY chromosomes for example there could be a mutation on or a
- 22:32
- deletion of that sry Gene and without that Gene acting on gonads these people
- 22:37
- could be chromosomally male but hormonally anatomically and phenotypically female and yes there are
- 22:44
- plenty of cases of women with swi syndrome getting pregnant and giving birth these are anatomically female
- 22:49
- chromosomally male women giving birth to healthy children and this can be done experimentally as well researchers have
- 22:55
- spliced an sry gene into mice with XX chromosomes or out of mice with XY chromosomes and cause them to develop
- 23:02
- anatomies and behaviors that are in STK contrast to their chromosomal sex even going so far is seeing XX mice develop
- 23:08
- male genitalia or having XY mice bearing litters and this happens out in nature as well even in mammals in African pygmy
- 23:15
- mice 75% of females have a y chromosome and an Sr y Gene and in the creeping BS
- 23:21
- here in the US all males have XX chromosomes these aren't anomalies or crazy mutations these are persistent
- 23:28
- evolutionary changes and even humans which have a y chromosome and an Sr y Gene still develop in the same estrogen
- 23:36
- Rich environment as every other embryo and if they don't produce enough testosterone to counteract that estrogen
- 23:41
- they could still develop as an anatomical female no matter what their chromosomes or what their genes look
- 23:47
- like but that's getting ahead of ourselves and talking about hormones we'll get to those in a minute going further with just genes and chromosomes
- 23:53
- there's also Turner syndrome which is the condition of having an X and then nothing else having just a y would be
- 23:59
- lethal but having Just One X is functionally the same as being chromosomally female because when you
- 24:04
- have two x's the second X doesn't really do much if you recall chromosomes are made of a thick rope of DNA and proteins
- 24:11
- called chromatin when that chromatin is loose and accessible the genes contained within it are able to be transcribed to
- 24:17
- make proteins we call this structure UK chromatin when the chromatin is wound tightly however the genes are
- 24:23
- inaccessible and functionally inactive we call that structure heterochromatin when someone has has 2 X chromosomes one
- 24:29
- of those X's ends up being scrunched down and condensed into a heterochromatic structure called a bar
- 24:35
- body with only about 15% of it being expressed at any given time and whether it's the first or the second X that gets
- 24:40
- scrunched up like this varies from cell to cell you could literally have two cells right next to each other one
- 24:47
- expressing the first X and the other expressing the second X this can be easily seen in calico cats which have
- 24:52
- the alals for either orange or black fur on their ex chromosomes the random distribution of orange or black color
- 24:58
- with in their coats is the result of the random inactivation of X chromosomes in their underlying tissues so if you think
- 25:04
- having either XX or XY chromosomes is the only thing that determines your sex then would someone with turner syndrome
- 25:10
- with only one X chromosome have half of a sex looking in the opposite direction triple X syndrome as the name suggests
- 25:16
- is when someone has three X chromosomes poly X syndrome is when someone has four or five X chromosomes Jacob syndrome is
- 25:23
- when they have one X and two y's and kleinfelter syndrome is any combination of multiple x's and one or more y's so
- 25:31
- XX y XX y y XXX y XXXX YY and on and on
- 25:37
- and on so again if you really think that having either XX or XY chromosomes is the only thing that establishes your sex
- 25:44
- then would someone with three or more sex chromosomes have multiple Sexes and the possibilities certainly don't stop
- 25:50
- there because there are some ways in which a person can have some cells inside their body which are chromosomally different than others one
- 25:56
- of the ways this can happen is mosaicism which usually occurs following a copying error early in development resulting in
- 26:02
- an individual developing from a single egg but possessing two or more cell populations with different genetic
- 26:07
- makeup mosaicism can affect any type of cell and can include whole sex chromosomes as well resulting in a
- 26:13
- person with a mixture of male and female cells and subsequently male and female traits and mosaicism isn't the only way
- 26:19
- in which you can have cells with different DNA inhabiting the same body chimerism occurs when two different egg
- 26:24
- cells are fertilized and then at some point in their development the embryos fuse meaning the resulting embryo will
- 26:30
- have two sets of cells with two different types of DNA fun fact this is also called reverse twinning which is an
- 26:36
- awesome name just like with mosaicism the tissues that end up being chimeric in these situations vary in each
- 26:41
- circumstance depending on which cells are traveling how they do it and where they settle chimerism usually doesn't
- 26:47
- show any signs or symptoms but sometimes when these people have children they find that they are more distantly
- 26:52
- related to them than they had expected with a son or a daughter being more genetically similar to a nephew or or a
- 26:58
- nie for example how Wild is that and also just like with mosaicism this can result in a person with a mixture of
- 27:05
- male and female cells and the unique proportion and distribution of those cells dictates that person's unique sex
- 27:11
- characteristics and all of that is just primary chimerism secondary chimerism can be the result of organ
- 27:17
- transplantation blood transfusion or if you've ever been pregnant before you may have experienced a phenomenon called
- 27:23
- microchimerism without even knowing it microchimerism is when fetal stem cells cross the placenta and implant
- 27:29
- themselves somewhere in the parents body or vice versa if you're chromosomally female and you've ever been pregnant
- 27:35
- with a chromosomally male child there's a chance that some of the cells and some of the organs somewhere in your body
- 27:41
- have XY chromosomes and some of your child cells have XX chromosomes and that's all totally natural the point is
- 27:47
- just like with all the different chromosomal configurations that we talked about earlier if xx and XY are all that matters how would we classify
- 27:55
- these people do they have multiple Sexes at once are different parts of their body different Sexes or can we just
- 28:01
- admit that some people exist outside the simplified binary framework a moment ago
- Genetic/Gonadal Sex
- 28:06
- I touched on how defining chromosomal females as having two x's is really about as useful as just saying that they
- 28:12
- don't have a y but having a why doesn't really mean anything on its own either
- 28:17
- remember certain genes are only going to be expressed at certain times under certain conditions and in certain
- 28:22
- tissues like for example some of the genes that produce sperm which are only ever going to be expressed in the testes
- 28:28
- so if I don't have testes for any of the reasons that we talked about earlier or any other reason then these genes do
- 28:35
- nothing and having them means nothing the point is even if you have a certain sex related Gene even if you have a
- 28:41
- whole sex chromosome you could still be missing any one of a dozen pieces of the puzzle of what sex determination
- 28:47
- actually is for example there was one study back in the 1980s that showed that female wallabies with XX alomes that
- 28:53
- didn't have any egg cells at Birth actually went on to develop testes even without an sry Gene and you know why
- 29:00
- it's because everybody watching this has the genes for both testes and ovaries
- 29:05
- what goads you get whether it's one or the other or neither or both comes down to an incredibly complex set of genetic
- 29:12
- interactions across several chromosomes most of which aren't even your sex chromosomes for example one of the genes
- 29:18
- that helps build testes is called s sox9 and it's found on chromosome number 17
- 29:24
- if you have ovaries that's because there's another gene on your ex chromosome called n r0 B1 which makes a
- 29:30
- protein called Dax one that stops s sox9 from giving you testes now chromosomal
- 29:35
- males have an X chromosome too but they also have a y chromosome which usually contains a gene called Sr Y which works
- 29:41
- by producing a protein which binds to nr0 B1 and stops it from making Dax one so that s sox9 can produce testes again
- 29:49
- that's why I have testes at this very moment it's because a gene made of protein that stopped another Gene from
- 29:55
- making a different protein that would have have otherwise stopped a different Gene from giving me the testes that I
- 30:02
- have how awesome is that it's also important to remember that some genes are pleotropic meaning they are one gene
- 30:08
- with several effects throughout the body a great example of that is s sox9 which isn't only responsible for testical
- 30:15
- development but also plays a role in skeleton development and it's even more important to remember that the three
- 30:20
- genes I just listed aren't even close to the end of the story there are plenty more genes at play here like w nt4 which
- 30:27
- is important for veloping ovaries and kidneys and even if I were to give you every single Gene that I could think of
- 30:33
- it still might not be the end of the story because there's evidence for other unknown genes which play some role in
- 30:39
- gonad development as well now if you're paying attention you might be starting to put some pieces together here like for example that you could have a
- 30:45
- perfectly functional Y chromosome but have a mutation on your sx9 gene or extra copies of your W4 Gene and so you
- 30:52
- still end up with female reproductive Anatomy or you could have no Y chromosome at all but you're missing an nr0 one gene or overex expressing an S
- 30:59
- sox9 Gene and so you still end up with testes and let's not forget the difference between heterochromatin and
- 31:05
- UK chromatin you could have all the right genes in all the right places but they're just wound a little bit too tightly so they're functionally turned
- 31:11
- off and yes there are other animals even other mammals that don't have an sry gene or even a y chromosome and yet they
- 31:18
- still have genetic sex differentiation and they still reproduce sexually none of these factors are guaranteed binary
- Hormones and Anatomical Sex
- 31:24
- sex switches but let's ignore all of that let's say you have have all the right chromosomes and all the right genes and whatever gonads that you like
- 31:31
- that still isn't good enough because it is the hormones that those gonads produce that actually causes you to
- 31:38
- develop as a male or a female or somewhere in between and hormones aren't nearly as simple as people like to
- 31:43
- pretend either for about as long as we've known what hormones are the idea of testosterone being the man hormone
- 31:50
- that makes you aggressive and estrogen being the woman hormone that makes you compassionate has been very popular
- 31:56
- science fiction however all all the way back in the 1930s scientists were noticing that both male and female
- 32:02
- animals interacted with both male and female hormones in pretty unexpected ways male horses were shown to possess
- 32:08
- striking levels of female hormones and female rats exposed to male hormones experienced female typical anatomical
- 32:15
- developments even male typical and female typical behaviors seemed to increase when lab animals were exposed
- 32:20
- to hormones of the opposite sex just like everything else in biology hormones got a lot more interesting the closer we
- 32:26
- looked at them and yet to this day lots of people are still very surprised to find that we all have testosterone and
- 32:32
- estrogen and all sorts of other hormones in our bodies all the time and they don't usually do what people think they
- 32:38
- do Endocrinology gets pretty complicated pretty fast so let me give you a very simplified example of a few key hormones
- 32:45
- so you can understand a little bit of what I'm talking about here you see some of the cholesterol in your body can be converted into progesterone and that's
- 32:51
- what becomes testosterone and that's what gives you what some of my anatomy professors would call male internal Plumbing some testosterone can then be
- 32:58
- converted into dihydrotestosterone and that's what gives you male external genitalia or
- 33:03
- testosterone can be converted into estrogen and estradiol and that's where you get female sex characteristics
- 33:09
- sometimes the same hormones can have different effects in different Sexes like the lutenizing hormone which triggers the ovaries to release eggs and
- 33:15
- the testes to produce sperm or a Stadol which signals the growth of female internal genitalia and also helps
- 33:20
- regulate erectile function all this is to say these different hormones are not male or female things everybody has all
- 33:27
- of these hormones in their bodies all the time and your specific hormone levels are as unique as your fingerprint
- 33:32
- it's also important to point out that hormones don't actually do anything by themselves all they can do is bind the
- 33:39
- cell receptors and then cause those cells to do things and those cell receptors are controlled by a totally
- 33:44
- different Gene pathway with just as much room for variation so for example you could have a daughter who hasn't had her
- 33:50
- first period by age 16 so you bring her to the doctor to figure out what's going on and you find out that she's actually
- 33:55
- chromosomally male but she has Androgen in Sensitivity Syndrome which means her cells aren producing The receptors to
- 34:00
- bind testosterone so even though she has XY chromosomes and more than enough testosterone to go around she is still
- 34:07
- anatomically and phenotypically female and if you think that's some wild and Fantastical scenario it's not Androgen
- 34:14
- Sensitivity Syndrome affects one in 20,000 people that's about the same rate as albanism and there are some ways in
- 34:20
- which more or less the same thing can happen in the opposite direction like some cases of congenital adrenal
- 34:25
- hyperplasia in which a chromosome will female would be exposed to high levels of androgens prenatally and so develop
- 34:32
- partially or fully masculinized external genitalia but who cares about all these chromosomes and genes and hormones and
- 34:39
- developmental stuff at the end of the day you're either born with a penis or a vulva right well not always in Western
- 34:46
- cultures sex is typically assigned at Birth based on a visual inspection of external genitalia and for that reason a
- 34:52
- lot of people tend to assume that external genitalia are a simple and unambiguous way to indicate sex in One
- 34:58
- Direction or the other but that is a super narrow Viewpoint and it couldn't be further from the truth to understand
- 35:03
- what I mean by that let's start by addressing the super common belief that we are all females by default and it's
- 35:09
- the Y chromosome that makes someone transform into a male that is a major oversimplification and the truth is way
- 35:15
- cooler at around 3 to 6 weeks of development regardless of your sex chromosomes all embryos look the same in
- 35:21
- fact this stage is called the indifferent stage but that doesn't mean that we're all phenotypically female
- 35:27
- there is no no male or female phenotype at this stage at around 5 weeks a structure called The urogenital Ridge
- 35:33
- will give rise to the wolfian and muan ducts if left unchecked the wolfian ducts will eventually develop into the
- 35:39
- ductus defin which used to be called vas defrin and the mearian ducts will develop into the uterine tubes which
- 35:44
- used to be called Fallopian tubes so it isn't that we all start out female most people start with the fundamentals of
- 35:51
- both male and female genitalia and usually one of those continues to develop while the other one is
- 35:57
- reabsorbed abbed however that isn't always the case for example a chromosomal male with persistent mulian
- 36:03
- duct syndrome will have a penis and testicles as well as all or part of a uterus and uterine tubes and maybe even
- 36:10
- the upper third of a vagina whereas a chromosomal female with muan a Genesis will lack those structures as genitals
- 36:16
- start forming from What's called the genital tubal at around 4 weeks you would still have no idea whether they're
- 36:22
- forming a penis or a vulva that whole region is so undifferentiated at this point that it takes another two full
- 36:28
- weeks just to separate your urethra and your anus before then you still have a singular lower orifice basically a cloa
- 36:36
- in fact the folds surrounding that orifice are even called gloal folds actual proper sexual differentiation of
- 36:41
- the gonads depends on signaling from what are called primordial germ cells this means that in order for things to go smoothly those primordial germ cells
- 36:49
- have to actually make it to the gonadal region to begin developing into an ovary a tesus or an ovotestis otherwise you
- 36:55
- end up with gatal dis Genesis we going ads simply don't develop at all this usually results in a person who is
- 37:00
- phenotypically female but doesn't menstrate and doesn't develop female specific secondary sex characteristics at puberty sexual differentiation of the
- 37:07
- genitalia is largely driven by hormones produced by the gonads so if there's a problem Upstream there's going to be a
- 37:12
- lot of changes Downstream as well but that isn't the only place those hormones come from for example you could have
- 37:17
- secondary hypogonadism which is when your hypothalamus and pituitary gland aren't producing enough androgens and so
- 37:23
- you get similar results to Androgen Sensitivity Syndrome because there simply Aren't Enough androgens to go around no matter how it happens through
- 37:29
- congenital adrenal hyperplasia or through Androgen and Sensitivity Syndrome or through secondary hypogonadism or through any other way
- 37:36
- the story is largely the same too many or too few of these hormones can masculinize or feminize the body in ways
- 37:43
- that may not be congruent with the person's chromosomal sex and to blur the lines even further one in every 2,000
- 37:48
- people are born with atypical or ambiguous genitalia meaning that their external genitalia aren't clearly
- 37:54
- defined and may not match up with their genetic sex or their other sex organs someone could be born with an enlarged
- 37:59
- clitoris that looks like a penis with an undeveloped penis that looks like a clitoris with a fused labia that looks like a scrotum with an unfused scrotum
- 38:06
- that looks like a labia or with an atypically positioned urethra which greatly enhances the ambiguity of any of
- 38:11
- those structures any one of those situations could easily result in a child being assigned the wrong sex at
- 38:17
- Birth and to complicate matters further ambiguous genitalia are usually surgically altered one way or the other
- 38:23
- often without the child's consent which is a whole other ethical bag of worms one of the more interes in examples of
- 38:28
- the kind of variation we can see in human sexual development comes from a small community in the Dominican Republic where around one in every 90
- 38:34
- children are known as GID does gidos children are chromosomally male but they're deficient in an enzyme called
- 38:40
- five Alpha reductase which converts testosterone to dihydrotestosterone which as I mentioned earlier is what
- 38:46
- causes you to develop male external genitalia as a result these children are born with external genitalia that are either Ambiguously or completely female
- 38:53
- and they're often assigned female at Birth and raised as girls that is until they hit puberty and start developing
- 38:59
- secondary sex characteristics typical of males and also start growing a phus and a scrotum and their testicles descent
- 39:06
- and that's where the word gados comes from it's derived from a Spanish slang word for testicles and the number 12
- 39:11
- which is when these kids usually hit puberty gavid do balls at 12 Research into this population shows that these
- 39:17
- children usually grow up to have the gender identity and take on the gender roles of a typical man we'll talk about
- 39:22
- what those words mean in a minute what's so important here is that if you're talking about chromosomal sex these people haven't changed at all but if
- 39:29
- you're talking about anatomical sex they just switch their sexes by totally natural means and no matter what layer
- 39:35
- of sex you're talking about there are many sex traits not just those found in the GD do which can change over time
- 39:41
- either anthropogenically or otherwise which makes sex a very complex and temporally fluid system and it means
- 39:48
- basing the entire system of sex assignment off of a casual glance at a baby's giblets is a major problem a
- Intersex
- 39:53
- little while ago I said that human sex determination could be broken down into four major steps establishing chromosomal sex establishing gonadal sex
- 40:01
- establishing anatomical sex and finally establishing phenotypic sex and since then we've talked about how every single
- 40:07
- one of those steps can be fuzzy and even Dynamic the chromosomal hormonal and anatomical variations we've been talking
- 40:14
- about here all fall under the umbrella of what are known as intersex conditions or dsds differences in sexual
- 40:20
- development the currence rate of individual intersex conditions varies between one and under 100 and one and a
- 40:26
- few thousand but even even at the most conservative estimates we're talking about tens of millions of people who
- 40:32
- fall outside of the supposed sex binary the UN estimates that 1.7% of the global
- 40:38
- population is interex and with a global population of around 8 billion people we
- 40:43
- would be talking about 136 million people that's a population
- 40:48
- the size of Russia imagine the leg work you have to do to hold on to this bizarrely parochial worldview that every
- 40:56
- single one of the over 8 billion people around the world fall perfectly into one
- 41:02
- of two distinct and discreet boxes unless they're Russians and even if we could agree that sex is a simple and
- 41:08
- uncomplicated thing for 98.3% of all of humanity that's no reason to gloss over
- 41:14
- the immense diversity within that last 1.7% I mean consider the fact that
- 41:20
- 99.9% of all atoms in the universe are either hydrogen or helium that's way
- 41:25
- more of a binary than human sex could ever be and yet it's not a reason to ignore the other 116 elements on the
- 41:32
- periodic table or call them anomalies and variations of hydrogen and helium there are tens of millions of intersex
- 41:39
- people out there their lives and experiences matter and they shouldn't be ignored or forced to conform to a strict
- 41:45
- binary for our convenience all this is to say simply having an X or a y
- 41:50
- chromosome is neither necessary nor sufficient for determining your overall biological sex there is is no standard
- 41:58
- template for male versus female development out in nature or in humans
- 42:03
- as it stands there are more than enough variations on the sex chromosomes alone to produce a female that is masculine
- 42:10
- enough or a male that is feminine enough to pass as the opposite sex both in Social Circles and even just to
- 42:16
- themselves the possibilities are simply too broad and the people they produce too diverse to reduce any part of
- Biological Thinking
- 42:23
- biological sex down to a simple binary even after all of this it's still very possible that there are still some of
- 42:29
- you out there that think all I'm doing is throwing out exceptions to the rules but the thing is in science finding
- 42:34
- exceptions to the rules is often what tells us that it's time to re-evaluate what we thought we knew about the rules
- 42:40
- in the first place that's how science has always moved forward but to understand what I mean by that you need
- 42:45
- to take a step outside of typological thinking for a moment let me explain what that means you see in biology we're
- 42:51
- taught to employ different kinds of thinking to approach different challenges and answer different questions under different circumstances
- 42:56
- an analog for this would be like learning kickboxing and Military strategy these are two different ways to think about conflict and one is going to
- 43:03
- be more useful than the other in different situations similarly there are lots of different ways to think about biological information and while
- 43:09
- thinking in terms of systems may be good for physiology it's going to yield different results when you're talking about ecology and it might be better to
- 43:16
- think in terms of networks there are lots of different types of thinking in this field but the big three that I want to focus on here are typological tree
- 43:23
- and population thinking typological thinking categorizes things into distin distinct essential groups with exclusive
- 43:28
- parts and clear boundaries this type of thinking is great for rapidly understanding major Concepts without much Nuance think about the first time
- 43:35
- you learned the difference between a plant cell and an animal cell for example but it's not as good for areas where things get fuzzy and gray like
- 43:41
- protus which have plant-like or animall likee cells but certainly aren't plants or animals tree thinking focuses on
- 43:47
- evolutionary relationships and the utility of adaptations it's great for when you see a new organism with
- 43:52
- familiar characteristics consider the evolutionary benefits of those characteristics and instantly understand a little bit more about that organism's
- 43:59
- life history and probably what it's related to as well however it's not always the best for addressing variations within a characteristic like
- 44:05
- wings on an insect versus Wings on a penguin population thinking accounts for and emphasizes variation it takes the
- 44:12
- entire population into account and helps to understand the Dynamics of that population for example when looking at a
- 44:17
- group of cancer cells and understanding which among them are most likely to metastasize but it's not great for telling you what cancer cells are or why
- 44:24
- they exist in the first place so when we're thinking about biological sex it can be very easy to want to boil things
- 44:30
- down into the simplified typological categories that we were first taught or to use tree thinking to think about it
- 44:35
- in terms of a reductive binary functionality but when you consider the full spectrum of sex looking across
- 44:41
- hundreds of different species especially humans who are the most studied animals on Earth these types of thinking are
- 44:46
- simply not appropriate in fact sometimes they're not even useful we would have so much deeper of an understanding of sex
- 44:53
- and so much less risk of dehumanizing people if we were to utilize population thinking and take into account all the
- 45:00
- beautiful variation of our global population so far we've talked about xxxy sex determination xxxz sex
- 45:07
- determination ZZ ZW sex determination environmental sex determination genic
- 45:12
- sex determination and how all of those vary beyond what a simple binary could contain but more than anything we've
- 45:18
- shown that it's next to impossible to talk about sex in a meaningful way without talking about development and
- 45:23
- any biologist will tell you that development covers your entire lifespan not just the point up to your birth your
- 45:30
- genotype stays more or less stable throughout your life but the way that it's expressed in the environmental
- 45:35
- factors around you change and so your sexual phenotype changes as well and that's no different than any other part
- 45:40
- of biology but all of that is only the first part of this video when you remember that sex is not the whole story
- 45:47
- of The Human Experience all the diversity we've talked about becomes a whole lot broader and a whole lot cooler

*** Part 3: Gender and Sexuality
- 45:58
- I mentioned earlier that when we talk about biological sex we sometimes need to specify as to whether we're talking about hormonal sex gatal sex chromosomal
- 46:06
- sex anatomical sex phenotypic sex and so on the key takeaway from that last section was that no one of those
- 46:11
- categories necessarily implies any of the others in this section we're going to be talking about how none of those
- 46:17
- categories are the same thing as words like man or woman just like how the words Theory and guess are used
- 46:23
- interchangeably in common parlaments but have very different meanings in terms of science the words sex and gender aren't
- 46:29
- nearly as synonymous as you might assume based on their day-to-day usage sex refers to the many anatomical and
- 46:35
- physiological characteristics of individuals who are male female or intersex whereas gender refers to the
- 46:41
- socially constructed roles Norms behaviors and characteristics of women men girls boys and non-binary people
- 46:48
- whereas sex is strictly biological gender is something that is designed and assigned by the individual experiencing
- 46:54
- it and others around them based on cultural habits and practices because gender interacts with but is
- 47:00
- fundamentally different from sex the two are often aligned but that isn't necessarily the case when someone's
- 47:06
- anatomical features match their own internal sense of their gender we call that person cisgender from the Latin
- 47:12
- prefix CIS meaning on the same side when they don't we call that person transgender using the Latin prefix trans
- 47:19
- meaning on the opposite side being transgender is not the same as being intersex these are distinct groups that
- 47:25
- may overlap but we should be careful not to conflate the two however we can use our understanding of intersect people to
- 47:30
- help highlight the distinction between sex and gender think back to the cases I talked about earlier of swi syndrome
- 47:36
- here we have someone who is chromosomally male but anatomically and phenotypically female they feel like a
- 47:42
- woman they dress like a woman they act like a woman they can get pregnant and they can give birth all while having XY
- 47:48
- chromosomes if sex and gender were truly synonymous then you would have to accept that this person is a man because they
- 47:55
- have XY chromosomes which means some men can give birth or you'd have to accept that they are a woman because they have
- 48:01
- female reproductive Anatomy which means some women have XY chromosomes neither of which is possible within a strict
- 48:07
- binary essentialist framework if however you simply separate sex from gender this all makes perfect sense being able to
- 48:14
- become pregnant is not a necessary condition of Womanhood so it has no real bearing here there are plenty of ways
- 48:20
- for the different aspects of sex to be in congruent and none of them necessarily need to line up with gender
- 48:25
- that makes this person interesting but nowhere near outside the realm of possibility people with Swire syndrome
- 48:31
- are no longer anomalous exceptions to the rules they're just people a common sticking point for people who are new to
- Comparing Social Constructs
- 48:37
- thinking about gender in this way is to wonder if gender is a social construct and is determined by someone's personal
- 48:43
- identity then why aren't other social constructs treated this way why for example would it be inappropriate to
- 48:50
- self-identify as another race in order to answer this question we need only compare any two other social constructs
- 48:56
- in order to see that the idea of different social constructs having different rules is something that we're already all familiar with whether we're
- 49:03
- conscious of that or not consider for example the social construct of money there are no wild dollar bills growing
- 49:09
- out in nature money is something that is invented by and maintained by generations of humans it isn't
- 49:16
- objectively real in any concrete way but it does affect our lives like gender
- 49:21
- money is something that you experience differently based on the circumstances of your birth and it means different things for for different people and
- 49:27
- different cultures at different times but unlike gender it's entirely determined by external factors its value
- 49:33
- is dependent upon group agreement and your relationship with it can be altered arbitrarily by your and other people's
- 49:39
- personal choices let's try another how about the social construct of marriage like gender it's reliant on aspects of
- 49:46
- your personal identity in this case sexuality which usually plays a big role in deciding who you're marrying but
- 49:51
- unlike gender it's not something that relies on self-identification instead it's largely a legal thing and it has
- 49:57
- measurable effects on your private property more than your body circling back to the social construct of race
- 50:02
- like gender it changes throughout history its dynamic in its presentation it impacts your social and political
- 50:07
- life and it's contingent upon truly arbitrary categorization systems but unlike gender which is rooted in culture
- 50:13
- and identity race is rooted largely in ethnicity despite there being far more diversity within so-called races than
- 50:20
- between them these two social constructs like almost any two social constructs are intersectional but not in any way
- 50:27
- interchangeable we'll talk more about self-identification in a minute but the point here is that when you stop to think about what a social construct is
- 50:33
- and does you'll very quickly realize that just like how everything that's considered to be a vehicle can't be
- 50:39
- categorized and utilized in the same way everything that's considered to be a social construct can't either it's also
- Gender Diversity
- 50:44
- important to remember that while gender is being constructed it's also being experienced this fact alone makes gender
- 50:51
- a highly multi-dimensional concept because we're not just talking about somebody's gender identity which is a
- 50:56
- core part of their individuality but also their gender expression their behaviors and appearances as well as
- 51:03
- their cultural expectations social status how to flaunt secondary sex characteristics and specific behaviors
- 51:09
- associated with these gender categories for this reason gender becomes pretty non-binary pretty fast but that's not a
- 51:15
- new thing for Humanity when we look across culture and throughout history traditional gender roles have been linked to things like socioeconomic
- 51:22
- status and power far more frequently than they've been linked to sex alone and there are a multitude of cultures
- 51:28
- across time and space that have more than two genders in their cultural construct even today after centuries of
- 51:34
- colonialism and Erasure hundreds of indigenous societies around the world still retain their long-established
- 51:40
- traditions of third fourth fifth and transgenders like for example the mahu
- 51:45
- of Hawaii the Hijra of India the quari wami of Peru the femin Yello of Italy
- 51:50
- the sakata of Madagascar the sister girls and brother boys of Australia and the wide array of trans and third gender
- 51:57
- identities across the native tribes of Continental North America which we collectively call two Spirits these are
- 52:02
- all diverse gender Traditions that live on to this day European cultures have enjoyed and been influenced by
- 52:07
- transgender people throughout history as well like chaler Deon a celebrated French diplomat Soldier and spy who
- 52:14
- fought in the Seven Years War although she was a signed male at Birth she lived openly as both a man and a woman at
- 52:19
- different times in her life which drew a lot of public attention at the time and then starting in 1777 she began to live
- 52:25
- permanently as a woman and was even officially recognized as a Woman by King Louis the 16th or how about Emperor
- 52:31
- Marcus aelius antoninus who ruled the Roman Empire around 218 ad she regularly
- 52:36
- wore makeup and wigs demanded to be referred to as a lady rather than a lord referred to herself as Queen not a king
- 52:43
- and offered great sums of money to any doctor who could change her physically into a female for this reason some
- 52:48
- museums have even Rewritten their plaques and information about antoninus using she her pronouns as would have
- 52:53
- been her preference as someone who is presumably a transgender woman or what about someone closer to home Christine
- 52:59
- Jorgenson served in the US Army during World War II before traveling to Denmark to transition somehow a letter to her
- 53:04
- parents was leaked to the press and since transgender people weren't really talked about at the time her return to the US was met with a lot of publicity
- 53:11
- she later went on to become an actress a recording artist and an activist for transgender acceptance even in the western binary framework that most of
- 53:18
- the world lives under today concepts of gender have changed a lot over the years before the 18th century when the concept
- 53:23
- of the cold and stoic Man became popular men were expected to exhibit a wide
- 53:29
- range of emotions and behaviors that certainly wouldn't be considered very manly today men would weep with emotion
- 53:35
- faint and distress they wore high heels and makeup and painted their fingernails and let's not forget about powdered wigs
- 53:42
- the early 20th century saw women rejecting Victorian ideas of femininity cutting their hair short smoking dancing
- 53:48
- seeking a more boyish style all things that wouldn't raise an eyebrow today but at the time were quite scandalous even
- 53:54
- our traditional Nursery colors of blue for boys and pink for girls didn't really come into being until around the
- 54:00
- 1940s before then dressing a boy in pink would have been all the rage but today there are men that won't even wear a
- 54:05
- pink T-shirt L it tarnish their masculine image even in this very moment
- 54:11
- I have my haircut relatively short and I'm wearing dark colors these are ways in which I can signal masculinity in a
- 54:17
- way that makes sense to me but neither of these things make me a man nor would I be any less of a man if I wasn't doing
- 54:24
- these things nor does it mean that any woman couldn't also cut her hair short and wear dark colors and Signal
- 54:30
- femininity by doing so nor does it mean that there aren't plenty of other ways that I could signal masculinity or
- 54:37
- plenty of other ways that I could use this exact system here to Signal any other gender expression just like
- 54:43
- language gender presentation is personal contextual Dynamic fluid and it's
- 54:50
- changing all the time and again all of that is just considering Western gender Norms over the past couple of centuries
- 54:56
- there are plenty of other cultures out there whose gender Norms have become more Progressive more regressive or who
- 55:02
- have been colonized and had their gender Norms Sur planted with new ones these are all examples of our attitudes views
- 55:09
- and practices surrounding gender changing over the course of multiple Generations none of which would be
- 55:15
- possible if gender were fixed and binary but all of which point to the idea that gender is less something that we are and
- 55:22
- more something that we do enact or even perform based B on our cultural
- 55:27
- surroundings you can even run a thought experiment on your own cultural norms at this very moment can a real man wear a
- 55:33
- dress can a real woman fix a car what about ordering a fruity cocktail or
- 55:38
- being the primary money earner of a household or knitting as a hobby or having hairy armpits or wearing nail
- 55:45
- polish or playing sports no matter what your answers are how many of them would your parents or your grandparents or
- 55:52
- your great great great grandparents have agreed with or what about the simple fact that phrases like real man and real
- 55:59
- woman exist in the first place if we can make intender comparisons whether they be meant as compliments or insults for
- 56:06
- example saying things like he should man up or he's more of a man than you then that implies that the manliness in
- 56:13
- question isn't something innate that you either have or don't based on your chromosomes or whatever but that it's
- 56:19
- spectral and precarious and needs to be maintained through performance when you think about it for more than 2 seconds
- 56:25
- you'll quickly realize that the gender roles and expressions and norms and biases and even definitions that we live
- 56:31
- under every single day are completely arbitrary while words like masculine and feminine have a general meaning in
- 56:38
- biology of pointing towards one of the two most common sex categories they don't really have a concrete meaning in
- 56:44
- terms of culture or gender because gender includes how a person experiences
- 56:49
- expresses and performs their identity within a cultural context it's going to
- 56:55
- end up being a reflection of that person and their society's expectations meaning
- 57:00
- there isn't ever going to be a definitive way to say for sure what it means to have a particular gender
- 57:06
- because gender varies from culture to culture from generation to generation and often from person to person as well
- 57:14
- despite the fact that this understanding of gender has been developed scientifically for about a century now
- 57:19
- lots of people still hold on to thoroughly debunked gender myths like for example the idea of men historically
- 57:25
- being the Hunter and women only being the gatherers and homemakers we have
- 57:30
- bountiful archaeological and ethnographic evidence of widespread feminine participation in hunting
- 57:36
- tracking meat processing and more one study which surveyed indigenous cultures from around the world found that women
- 57:42
- participated in hunting in 79% of the society studied and that wasn't limited
- 57:47
- to small game either these were big game Hunters who are out there putting in the hard work with the exact same
- 57:54
- specialized Knowledge and Skills as their masculine counterparts and yet just like the myth of your either XX or
- 58:01
- XY the myth of man the hunter still persists to this day people look at the
- 58:06
- gender roles within our own culture and assume that that is the natural ground state of all Humanity going back to the
- 58:12
- beginning of our species it's a glaring example of cultural bias cloud in scientific thinking the truth is no
- Sex vs. Gender in Nature
- 58:19
- matter how you slice it gender can neither be boiled down to nor predicted by sex what western cultures consider
- 58:26
- natural behaviors for males and females are not universals among animals mammals primates or even peoples and if you
- 58:33
- still don't believe me let's take a look around the animal kingdom and see just how useless gender would be as a
- 58:38
- category if it truly were a Sex Link trait starting with the basics of sexual dimorphism there are plenty of species
- 58:44
- out there where the females are bigger and stronger than the males and there are also plenty of species where the males and the females are completely
- 58:50
- indistinguishable there are even some species where the males can take on several forms some of which resemble the
- 58:56
- females or species like hyenas where the females have a fully erectile pseudo penis which makes it very difficult to
- 59:02
- distinguish them from the males unless you dissect them first or species like ringtail lemurs where the females have a
- 59:07
- long and phallic clitoris which is transverse by urethra which makes the whole thing look and act an awful lot
- 59:12
- like a penis as well and if you think that a phus with an accessory urethra is an impossibility in human females you'd
- 59:18
- be dead wrong but we already covered that stuff earlier there are some species like DAC fruit bats which exhibit paternal lactation meaning it is
- 59:25
- the Mal that produce milk to feed their young while male lactation is relatively rare at the species level the ability
- 59:31
- for any given male to produce milk certainly is not even most human males have mamory glands that can be triggered
- 59:37
- to develop and produce milk under the right circumstances there are some species where the females deposit eggs
- 59:43
- into the males and then the males give birth there are some species where the males not the females tend to the nest
- 59:48
- and watch over the eggs there are other species where they take turns there are plenty of species including some of our
- 59:53
- closest relatives which are completely matriarch Aral meaning it is the females that are in charge and control their
- 59:59
- whole group and a strong dominant male would not make it very far if gender truly was easy to Define and linked with
- 1:00:06
- sex then all this variation which exists well outside of the Norms of our own culture would be impossible to maintain
- Sexuality
- 1:00:14
- it's also incredibly common for new Learners to confuse gender and sex with sexuality and to assume that these
- 1:00:20
- discussions of genes hormones Anatomy roles identities and behaviors
- 1:00:26
- necessarily implies information about attraction intimacy eroticism and
- 1:00:31
- romance but sexuality is yet another completely different thing that exists
- 1:00:37
- on a vast spectrum of preferences and behaviors and even that Spectrum can be
- 1:00:42
- further broken down into more specific Spectra based on who you're romantically or sexually attracted to which may or
- 1:00:50
- may not line up for example an a-romantic person is someone who doesn't experience romantic attraction
- 1:00:56
- and that's different from asexuality which is a lack of sexual attraction a couple of things that we can say that
- 1:01:02
- sexuality and gender have in common is that they're traditionally associated with socioeconomic status and power and
- 1:01:07
- that they display Rich diversity across cultures and throughout history there are plenty of cultures out there which
- 1:01:12
- categorized and recognized sexualities in totally different ways than we do today if they even labeled certain
- 1:01:18
- sexualities at all our current labeling system for different sexualities is a very modern invention which doesn't
- 1:01:24
- really work outside of our cultural fre framework which is why it's sometimes so difficult to pin somebody's sexuality
- 1:01:29
- down to just one category within our limited language looking across the animal kingdom we've observed homosexual
- 1:01:34
- behavior in over 1,500 animal species there are even some species which are entirely bisexual like bonobos or
- 1:01:42
- entirely homosexual like the parthenogenic whiptail lizards that we talked about earlier if any other trait
- 1:01:47
- Behavioral or otherwise had been observed to be as ubiquitous across the animal kingdom as samex sexual behavior
- 1:01:54
- it would not be the Le least bit controversial to call that trait ancestral or maybe even advantageous as
- 1:02:01
- far as Evolution and development are concerned we're still not entirely sure where homosexuality comes from but
- 1:02:06
- there's strong evidence that there's at least some genetic component to it in monozygotic or identical twins twins
- 1:02:12
- that share the same DNA if one twin is homosexual there's a significant chance that the other one will be as well
- 1:02:19
- whereas in dizygotic or fraternal twins that chance drops significantly and in non- Twin siblings the chance is about
- 1:02:25
- the same same as it would be for any two random people but genetics aren't the only factor which appear to be at work in determining one's sexuality there's
- 1:02:32
- some evidence that hormones may be at play here as well for example in one study female zebra finches which were
- 1:02:37
- injected with a common feminizing hormone very early in their lives were more likely to exhibit male typical
- 1:02:42
- behaviors and choose females as mates some of them even develop male typical color patterns however we can't be sure
- 1:02:49
- whether these sort of things are due to some change in the structure or function of the brain or if it's somehow
- 1:02:54
- extending the sensitive period for sexual imprinting or if there's some other Factor at play and none of this
- 1:02:59
- rules out environmental influences or epigenetic changes that could be allowing those different factors to take
- 1:03:05
- effect just like with genes hormones appear to be a piece of the puzzle but they certainly aren't the whole picture
- Dangerous Pseudoscience
- 1:03:11
- it's all just a little bit too complicated for that speaking of environmental influences there is an unfortunately common myth that social
- 1:03:18
- pressure can influence somebody's sexuality or gender identity especially at a young age now is a great time to
- 1:03:25
- point out that there is absolutely no evidence to support that and strong evidence against it there is evidence
- 1:03:31
- that social networks play a role in the spread of certain sexual behaviors such as the age frequency and level of safety
- 1:03:38
- at which adolescence engage in sexual activity however there is no evidence that the same kind of social influence
- 1:03:44
- and peer pressure can change someone's sexual orientation or gender identity and that isn't for lack of trying there
- 1:03:50
- is actual scientific research looking for that kind of influence and there are plenty of horri Ric real world examples
- 1:03:57
- of people trying to forcibly change someone's sexual orientation or gender identity none of it works one case study
- 1:04:04
- into this very thing was a man named David rmer he was born in 1965 and due to an equipment malfunction during
- 1:04:10
- circumcision his penis was irreparably damaged his parents sought the help of Dr John money at John Hopkins University
- 1:04:17
- who used the boy to test his ideas that people were born neutral in our gender identities and that we were socialized
- 1:04:23
- into being the genders that we are following Dr money's instructions David underwent full sex reassignment surgery
- 1:04:29
- and began to be raised as a girl but by the time he reached adolescence it was very obvious that he was having a hard
- 1:04:36
- time identifying as a girl and before long without even knowing the circumstances of his birth David began
- 1:04:43
- to threaten suicide if his parents wouldn't let him be a boy later in life
- 1:04:48
- David learned what happened to him changed his name became a husband and a father and went public with his story in
- 1:04:55
- order to Des credit Dr money's research David's tragic story along with the consistent findings of modern research
- 1:05:02
- thoroughly debunk these sadly popular ideas that being gay or transgender are
- 1:05:08
- examples of social contagions or maladaptive trauma responses they also
- 1:05:14
- categorically rule out the ideas that somebody can be turned gay or straightened out and they've prompted
- 1:05:20
- scientific and medical communities to re-evaluate the ways that they deal with non-binary transgender and intersex
- 1:05:27
- people and to develop new measures to prevent harm in children and adults alike who may be struggling with their
- 1:05:33
- gender identities these data fall perfectly in line with our understanding of sexuality and gender as being
- 1:05:40
- relatively stable parts of a person's identity which while not fully understood are certainly not dependent
- 1:05:47
- upon fashion or social conditioning which is one of the major reasons that all of these professional organizations
- 1:05:54
- which collectively represent millions of licensed medical and Mental Health Care Professionals have made
- 1:06:00
- public statements denouncing conversion therapy as the dangerous
- 1:06:06
- pseudoscientific nonsense that it is Research into sexual orientation is incredibly important but just like the
- 1:06:13
- rest of the things in this video there's a lot that we still don't know and unfortunately that knowledge can only be
- 1:06:18
- gained by people being very honest with complete strangers about really intimate
- 1:06:24
- personal information that that historically has been seen as pretty taboo so it may be a little while before
- 1:06:29
- we have a more complete understanding of all this stuff what we already know for sure though is that sexuality is yet
- 1:06:35
- another Spectrum so looking for one single cause that produces a clear-cut outcome is a Surefire way to miss out on
- Self-Identification
- 1:06:41
- a real understanding of what's actually going on there the cultural dynamics of gender along with its deeply personal
- 1:06:47
- and fluid nature means that the labels associated with gender identity necessarily rely on
- 1:06:53
- self-identification and this is a major stick point for people who think that self-identification renders gender
- 1:06:59
- overly subjective recursive or impossible to confirm however self-identification is an inherent part
- 1:07:05
- of social identity in general so it's not like this is a New Concept that just came along with gender in fact we can
- 1:07:11
- actually use the spectrum of sexuality as a great example as to why the self-identification model is not only
- 1:07:18
- functional but the most effective way to identify someone's gender when we talk about sexuality it's important to
- 1:07:24
- remember that there may may not be a single simple specific term to
- 1:07:29
- adequately describe someone's sexual orientation and the terms that we do use sometimes mean different things to
- 1:07:35
- different people this is because there's simply no way to fully and adequately account for all of a person's feelings
- 1:07:42
- about something so complex while simultaneously crushing those feelings down into a single categorical label
- 1:07:48
- that can be reliably applied elsewhere instead the terms we use are just tools for self-expression allowing people to
- 1:07:56
- describe their experiences in ways that are meaningful to them and gender works
- 1:08:01
- the same way the terms we use are neither diagnostic nor Universal so each person who identifies themselves using a
- 1:08:08
- term like man woman boy girl or non-binary also defines that term for
- 1:08:13
- themselves these identities are descriptive not prescriptive reflecting what matters most to the individual
- 1:08:20
- about the roles behaviors expressions or even physiology that they associate with
- 1:08:25
- that category when someone earnestly refers to themselves as a man or a woman
- 1:08:31
- all we know for sure is that they are a person who self-identifies as and aligns their gender identity to the social
- 1:08:38
- cultural and personal traits that they associate with manhood or Womanhood
- 1:08:43
- there is no other way to define these terms so that they include all CIS and trans people of one category and exclude
- 1:08:51
- all CIS and trans people of any other category it's also critically important to remember that even just the words
- 1:08:58
- transgender non-binary gay bisexual and so on are themselves products of a
- 1:09:05
- eurocentric framework of gender and sexuality which assumes that cisgender heterosexuals are the natural standard
- 1:09:12
- and that everybody else's existence needs to be justified rather than accounted for this perspective ignores
- 1:09:19
- the fact that there are plenty of cultures out there that have all had the same kinds of people but with completely
- 1:09:25
- different lines and distinctions than the ones that we're hashing out here beyond that it ignores that nature
- 1:09:30
- itself has presented us with a complex and diverse spectrum of chromosomes and
- 1:09:36
- anatomies and hormones and behaviors that often defy the rigid oversimplified
- 1:09:42
- categories that humans have created this is not unique to science especially to
- 1:09:47
- biology and we need to quit pretending like it is it is only because we are looking through the narrow lens of our
- 1:09:54
- CIS centered and heteronormative culture that we treat diverse genders and sexualities as anything less than yet
- 1:10:01
- another exciting part of the rich tapestry of biology as I said in the beginning of this video we are not
- 1:10:08
- special we're just animals the one thing that sets us apart in all of this is
- 1:10:14
- that we are the only animals that can communicate in great detail what it feels like to have a particular gender
- 1:10:21
- or a particular sexuality and what it means to experience those things in the cultural context surrounding us we
- 1:10:28
- should not be afraid of the perceived differences between Cy and trans or straights and gay or any of this we
- 1:10:35
- should be excited for the opportunity to learn new information about how life really works rather than just trying to
- 1:10:41
- cram things down into boxes all the time if we want to understand what it means
- 1:10:46
- to be human or what it means to be anything we need to be focused on science and be listening to the people
- Neuroscience
- 1:10:53
- who are living the lives that we want to understand and we can gain a glimpse of that understanding when we look directly
- 1:10:59
- into the human brain historically the concept of sexual dimorphism in human brains originated from observations in
- 1:11:06
- other animals where certain brain regions which were usually tied to reproductive behaviors like vocal control regions and song birds for
- 1:11:12
- example show dramatic differences between the Sexes and so it was largely assumed that human brains would show the
- 1:11:17
- same kinds of dimorphism but when we looked more closely we found that it wasn't necessarily so easy for example
- 1:11:23
- one study on quailes found that there was a critical period for hormone exposure in the brain and when researchers gave Quail embryos
- 1:11:29
- masculinizing or feminizing hormones at this stage the resulting adults would behave more like a male or a female
- 1:11:35
- based on the hormones they received rather than their chromosomal or anatomical Sexes fast forward to looking
- 1:11:41
- at human brains and we see that the same thing is true brain development and function are not solely determined by
- 1:11:46
- genetic sex but are actually influenced by a complex array of hormonal environmental and even social factors
- 1:11:53
- and this Dynamic dance of stim Uli is what creates the complexities of our gender identities whether we're CIS
- 1:11:59
- trans non-binary or whatever while some sex differences do exist in the brain the magnitude of these differences is
- 1:12:06
- far smaller than in other species for example the third intertial nucleus of the anterior hypothalamus or the inah3
- 1:12:13
- is around 1.6 times larger in human males than it is in human females whereas a homologous region in rats is
- 1:12:19
- around five times larger in males rather than females so when we talk about structural differences within the brains
- 1:12:25
- males and females of other species we're sometimes talking about differences that are so prominent you can see them with
- 1:12:30
- the naked eye in humans however we're talking about clusters of neurons that are around the size of a grain of rice
- 1:12:35
- there are other notable regions like the central subdivision of the bed nucleus of the stri terminalis or bstc and the
- 1:12:42
- sexually dimorphic nucleus of the preoptic area or sdn POA both of which are usually larger in males than in
- 1:12:48
- females but the key is because hormones seem to play a bigger role in brain development than sex chromosomes do the
- 1:12:54
- sizes of the brain regions tend to reflect someone's gender identity rather than simply their sex assigned at Birth
- 1:13:00
- through all of this it's crucial to emphasize that the concept of brain sex as it used to be understood is a very
- 1:13:06
- outdated model it is true to say that certain sex hormones play a critical role in shaping the brain during both
- 1:13:11
- pre- and postnatal development however there are plenty of other factors like gene expression hormone receptor
- 1:13:18
- distribution and even individual experiences which also play a major part in brain development and can
- 1:13:25
- dramatically influence the degree of maleness or femaleness within brain structure and function most of the brain
- 1:13:31
- differences which were once attributed to sexual dimorphism have since been shown to actually be quite small with a
- 1:13:36
- ton of overlap between sexes in fact modern research has shown that human brains exhibit a wide variety of
- 1:13:42
- characteristics which were once considered male typical or female typical creating a unique Mosaic pattern
- 1:13:48
- for each individual and a lot of variation across populations one review of over 1,400
- 1:13:55
- human brains found that sex differences between the brains were neither highly dimorphic nor internally consistent
- 1:14:01
- instead each and every one of the brains was a varied composite of diverse features putting the brain along with
- 1:14:09
- everything else about sex on a spectrum the most consistent sex difference between male and female brains tends to
- 1:14:15
- be overall volume and development time with male brains being slightly larger simply because male bodies are slightly
- 1:14:22
- larger and female brains finishing develop earlier but none of that really translates to a major difference in
- 1:14:28
- functionality and all this complexity makes it difficult to say that anybody not just Cy or trans people have brains
- 1:14:34
- that truly completely structurally match their gender identities but what does
- 1:14:40
- point in that direction is the fact that brains adapt to experiences the connections between neurons break and
- 1:14:46
- build and reorganize all the time and as they do whole brain regions can change
- 1:14:52
- we call this quality neuroplasticity so when we want to look for gender specific differences in the brain we often need
- 1:14:58
- not look much further than gender specific experiences which create gender specific plastic responses that is to
- 1:15:05
- say as we lead gendered lives and have gendered feelings we develop somewhat gendered brains let me give you an
- 1:15:11
- example people who have lost limbs sometimes experience what's commonly known as Phantom Pain where their brain
- 1:15:17
- is so sure that the Lost limb is still there that the patient suffers pain in a part of the body that no longer exists
- 1:15:24
- interestingly some transgender people have been shown to experience their own kind of phantom pain only instead of
- 1:15:30
- experiencing pain in a limb that they have lost they feel a part of their body that they've never had before like
- 1:15:36
- breasts or wide hips or even certain genitalia we can also learn from how our brains perceive our own bodies like one
- 1:15:43
- notable study in which CIS and trans people had their brains monitored while they watch computer-generated images of
- 1:15:49
- their own bodies morphing to become more masculine or more feminine and sure enough the same brain regions lit up in
- 1:15:55
- trans people watching their bodies morph away from their assigned sex as in Cy people watching their bodies morph
- 1:16:01
- towards it as it is the relationship between brain structure and development and their association with gender
- 1:16:07
- identity is not fully understood and more research is needed to draw more definitive conclusions however it seems
- 1:16:13
- clear that the brain is far more Mosaic than dimorphic the idea of male and female brains oversimplifies a far more
- 1:16:20
- Dynamic and individualized phenomenon at face value there seem to be no more male or female brains than there are male or
- 1:16:26
- female hearts or male or female lungs but there are gendered patterns of brain responses which are produced by gendered
- 1:16:33
- patterns of stimuli in the world around us and we consistently see that the activation patterns within transgender
- 1:16:39
- people's brains match those that we would expect to see in someone with their gender identity not their assigned
- 1:16:44
- sex of birth oh and by the way there's a ton of research showing a neurobiological component to diverse
- 1:16:49
- sexualities as well for example functional MRI scans show the same brain regions behaving in the the same way in
- 1:16:55
- homosexual men and heterosexual women observing an image of a man's face and sure enough in homosexual women and
- 1:17:02
- heterosexual men the exact same brain regions do the exact same things with a woman's face there are also other
- 1:17:08
- studies which point to certain brain regions which may be larger or smaller in homosexual or heterosexual
- 1:17:14
- individuals and just like with gender the evidence increasingly points to a vast array of neural factors which may
- 1:17:20
- or may not be associated with sexual orientation all of this makes interpretations of the meanings of these
- 1:17:27
- connections just as murky as those drawn from brain differences between Sexes all that being said as we continue to study
- 1:17:33
- these things it's important that we take care not to pathologize LGBT identities not only is it abundantly clear that
- 1:17:40
- these are not diseases or disorders but emphasizing differences in order to explain perceived anomalies can lead to
- 1:17:47
- people justifying discrimination as we work to interpret these data it's crucial that we also work to temper our
- 1:17:54
- social social and cultural heris surrounding gender and sexuality so that we don't unduly influence our scientific
- 1:18:00
- understanding or risk perpetuating harmful stereotypes so if you've been following along we've covered a variety
- 1:18:07
- of possibilities in chromosomes in hormones in internal and external genitalia in gender in sexuality in
- 1:18:14
- brains in culture and in history we've talked about how you can have XX chromosomes and still have a penis we've
- 1:18:20
- talked about how you can have XY chromosomes and still get pregnant we've talked about how you can have ovaries or testes or a penis or a uterus or neither
- 1:18:28
- or both or more than one of one or the other which happens from time to time and through it all the point remains if
- 1:18:34
- you really really want to hold on to this idea that every single person fits
- 1:18:39
- into just one of however many boxes you are very quickly going to have to come up with dozens if not hundreds of
- 1:18:46
- categories just to hold on to this insanely parochial worldview you're keeping the genetic chromosomal
- 1:18:53
- biochemical hormonal gatal anatomical and physiological characteristics
- 1:18:58
- traditionally associated with so-called males and females are far more complex than people tend to assume sex is not a
- 1:19:06
- binary system with only two mutually exclusive outcomes and gender by its
- 1:19:12
- very definition as a social construct adds yet another layer of infinite
- 1:19:17
- variation and that's why it's not only more scientifically accurate but just so
- 1:19:23
- much easier to say that sex and gender exist on a spectrum and while it's
- 1:19:29
- entirely possible that you're 100% male or 100% woman whatever that would mean
- 1:19:34
- it is at least equally possible that you fall somewhere along this fuzzy gradient
- 1:19:40
- and that shouldn't bother you it should make you curious but to go on spewing
- 1:19:46
- nonsense like XX means girl and girls dress like this or XY means boy and boys
- 1:19:52
- act like that is not only prop ously inaccurate it is cruel and dangerous

*** Part 4: From Science to Society
- 1:19:58
- which brings me to why all this stuff matters outside of biology
- 1:20:06
- class over the course of this video we've talked about how sex and gender are different things how they aren't
- 1:20:12
- necessarily congruent and how neither one is a true binary this is especially true of gender which by its very nature
- Gender and Health
- 1:20:18
- cannot be expected to reliably present itself in predictable ways but just because gender is a social construct
- 1:20:24
- that doesn't mean that it has no bearing on reality just like other social constructs like law marriage race and
- 1:20:30
- money gender has big impacts and big implications at both the individual and
- 1:20:36
- societal levels for example gender has a direct influence on people's experiences with and sometimes even their access to
- 1:20:43
- healthcare not only because of gender bias and discrimination among healthc Care Professionals but also because of
- 1:20:48
- systemic gender inequalities within societies typically women and girls experience greater barriers to accessing
- 1:20:54
- ad quate healthare than men and boys these barriers include but aren't limited to restrictions on their
- 1:20:59
- Mobility lack of access to medical information reduction or removal of decision-making power lower literacy
- 1:21:05
- rates discrimination from their provider and their community and sometimes even lack of training and awareness among
- 1:21:12
- healthc care providers of the specific needs of anatomical females consequently women and girls face greater risks of
- 1:21:18
- unintended pregnancies sexually transmitted infections cancer malnutrition Vision impairments
- 1:21:23
- respiratory infections genital mutilations elder abuse and much much more when it comes to transgender people
- 1:21:29
- this situation compounds due to the tremendous amount of misinformation and fearmongering surrounding what's known
- 1:21:35
- as gender affirming care which is specialized medical care which attempts to reduce the in congruence between a
- 1:21:41
- person's gender identity and their phenotypic sex when we talk about gender affirming care people often assume that
- 1:21:47
- we are talking about extreme surgeries performed only on transgender people
- 1:21:52
- however that isn't the case in fact most gender affirment care including things like hair plugs lip fillers hormone
- 1:21:59
- therapies laser hair removal breast augmentation breast reduction breast tissue removal erectile dysfunction
- 1:22:06
- treatments facial feminization or masculinization surgeries and even puberty blockers are utilized more often
- 1:22:13
- than not by cisgender people usually to help align their physical appearance with their gender identities exactly the
- 1:22:20
- same as when these treatments are given to transgender people unfortunately despite the fact that every Major
- 1:22:26
- Medical Association in America recognizes the validity of transgender people and the vital role of gender
- 1:22:33
- affirming care in improving their mental and physical well-being despite the fact that studies have consistently shown
- 1:22:39
- that age appropriate and evidence-based gender affirming care protects transgender people from a greater
- 1:22:44
- incidence of anxiety depression and self harm despite the fact that we have standards of care and clinical
- 1:22:51
- guidelines which are widely accepted for transgender adults and children alike
- 1:22:56
- which recommend a staged process of transition which allows these individuals to explore their gender
- 1:23:02
- identities while keeping their options open and despite the fact that the regret rate for these interventions is
- 1:23:08
- significantly lower than many common treatments and surgeries that nobody takes issue with people and politicians
- 1:23:16
- alike are attempting to demonize or even deny gender affirming care specifically
- 1:23:21
- and only for transgender people because it conflicts with ideology rather than their understanding of the evidence
- 1:23:28
- gender dysphoria is the distress caused by the discrepancy between an individual's gender identity and their
- 1:23:33
- sex assigned at Birth not all transgender individuals experience gender dysphoria sometimes it can be
- 1:23:39
- treated with social transition alone sometimes medical interventions are necessary sometimes it abates with
- 1:23:45
- puberty sometimes puberty makes it much much worse in any and all of these
- 1:23:51
- situations it is imperative that transgender people will be allowed to explore their options and to effectively
- 1:23:57
- align their genders with their bodies under the safe and supportive care of a physician because when they are not
- 1:24:05
- afforded that opportunity the results can be exactly as dire as you would expect when a person is forced to live
- 1:24:12
- in a way that is in direct conflict with their identity as of right now suicide is the second leading cause of death
- 1:24:19
- among people from the ages of 10 to 14 and the third leading cause of death among people from the AG ages of 15 to
- 1:24:25
- 24 it outranks all major illnesses lots
- 1:24:30
- of young people think about it I thought about it at that time but LGBT people in
- 1:24:35
- those age groups are almost five times as likely to have attempted suicide than
- 1:24:41
- their cisgendered heterosexual peers and what's worse LGBT youth who report
- 1:24:46
- coming from non-accepting or non-supportive families are eight times as likely to have attempted suicide than
- 1:24:53
- other LGBT youth so we're talking about people who are eight times as likely as
- 1:24:58
- the people who were already five times as likely as the people who were already
- 1:25:03
- at a high risk of attempting suicide that is a major problem that deserves
- 1:25:09
- serious attention and if there was anything anything at all that could
- 1:25:15
- reduce that risk even a little bit it should at least warrant your sincere
- 1:25:20
- consideration and all of this is hugely exacerbated by the Deluge of charlatans
- 1:25:26
- grifters and pseudo intellectuals in media and politics who point to these high rates of suicide and depression as
- 1:25:33
- evidence that diverse genders and sexualities are tanam out to mental disorders when all it really
- 1:25:38
- demonstrates is that these people don't understand the difference between correlation and causation and that these
- 1:25:44
- poor kids are being treated like perverts and freaks for just trying to exist it also doesn't help anybody to
- 1:25:50
- suggest that we should be keeping discussions of gender and sexuality away from children not only does it ignore
- 1:25:56
- the fact that children are exposed to depictions of cisgender people and heterosexual relationships all the time
- 1:26:02
- whether they be in fairy tales or family sitcoms or history class it also assumes
- 1:26:07
- that LGBT people were never children before research shows that these kids
- 1:26:12
- know who and what they are long before they have the vocabulary to articulate it and by denying them the same levels
- 1:26:20
- of age appropriate representation and education that we afford every everybody else we're spreading the harmful message
- 1:26:27
- that their thoughts feelings and identities are something to be ashamed of and hidden away as well as fueling
- 1:26:34
- the exact same kind of bullying and stigmatization that leads to Serious harm in any children and because of our
- 1:26:42
- cultural attitudes surrounding gender the risks for women girls and those with diverse gender identities continue well
- 1:26:49
- into the outside world and throughout their entire lives gender-based Stig and discrimination puts these people at
- 1:26:56
- significantly higher risk of both physical and sexual violence and when it comes to trans people those numbers
- 1:27:03
- increase dramatically trans people across the board both men and women alike are over four times as likely to
- 1:27:10
- experience sexual assault aggravated assault rape and other forms of violence
- 1:27:15
- as their cisgender counterparts and circling back to self harm it turns out when you're consistently the victim of
- 1:27:22
- systemic discrimination and normalized physical violence it takes a toll on your mental health even looking Beyond
- 1:27:28
- trans and gender diverse people the gender Norms that we live under themselves can be harmful if not
- 1:27:34
- regulated as we see for example in men and boys who are more likely to take
- 1:27:40
- unnecessary risks with their mental physical and Sexual Health abuse drugs and alcohol smoke tobacco and even
- 1:27:47
- refuse mental and physical health care all in the interest of appearing tough and manly and those same emotionless
- 1:27:55
- hypersexual and dominance oriented gender Norms lead to men and boys being the perpetrators of physical and sexual
- 1:28:02
- violence as well as failing to report on instances in which they are the victims
- 1:28:07
- of that same violence these are all examples of widespread gender specific
- 1:28:12
- patterns of violence harm and death that we could be working to eliminate but first we've got to come to grips with
- 1:28:19
- the functions and implications of gender and stop pretending like this is all just some Modern political ideology but
- 1:28:26
- if the biggest problem you're having in the 21st century is what people's genitals look like and what they're
- 1:28:33
- doing with their genitals in the company of other consenting adults if that is the needle on your moral compass I
- Gender and Science
- 1:28:41
- strongly encourage you to re-evaluate your priorities looking outside of the interests of direct human harm reduction
- 1:28:47
- improving our understanding and attitude surrounding gender is beneficial to progress as a whole a lot of scientific
- 1:28:54
- research has been done under the outdated binary framework which often conflate sex and gender together having
- 1:29:00
- recognized this issue lots of scientists and even major science organizations are working to establish meaningful ways to
- 1:29:07
- measure sex and gender as non-binaries in surveys research studies job applications clinical settings and more
- 1:29:14
- after all if we've been doing research using definitions and dichotomies that are at best ineffective and at worst
- 1:29:21
- inaccurate then how does that research stand up it's it's certainly not useless but it's undeniable that we could be
- 1:29:27
- learning new things faster if we were to use more accurate and more inclusive models of sex and gender when gathering
- 1:29:34
- and analyzing data the very idea that sex and gender are synonymous and locked
- 1:29:39
- in a strict and immutable binary despite all the evidence of the contrary and the
- 1:29:44
- lived experiences of millions of trans and intersex people exemplifies the kind
- 1:29:50
- of unnecessarily rigid and dualistic thinking that impedes both social progress and scientific discovery
- 1:29:57
- however recognizing the nons synonymous and non-binary nature of things like sex and gender not only opens the door for
- 1:30:04
- accepting and celebrating the immense variation we see within human bodies minds and existence it also paves the
- 1:30:12
- way for improving the way that we do research into things like Evolution and development as well as how we tackle
- 1:30:19
- things like healthare education social policies and so much more that's why
- 1:30:24
- back in 2022 the nationaly of Sciences engineering and Medicine put out this consensus study report on how to better
- 1:30:31
- measure and Report things like gender identity sexual orientation and sex as a non-binary construct all to expand our
- 1:30:39
- research efforts beyond the restrictive dualisms of male and female or man and
- 1:30:44
- woman or homosexual and heterosexual because as it says right in the introduction the use of a single binary
- 1:30:52
- male female item to measure sex does not capture either the multi-dimensional nature of this construct or its
- 1:30:59
- underlying complexity for those with intersex traits or transgender people because their sex traits may not
- 1:31:05
- correspond to those of a single sex introducing a third response category to Binary measures of sex such as
- 1:31:12
- transgender or interex is thus a poor measure of these populations moreover
- 1:31:17
- because gender is socially mediated binary measures of any dimension of gender are also inadequate for Capt
- 1:31:23
- capturing the complex ways in which individuals can identify with Express or socially experience gender the reality
- Summary
- 1:31:31
- is that sex and gender are far from cleancut Concepts we're still learning all the pieces that go into sex
- 1:31:37
- determination as well as where gender even comes from let alone what it actually is we should expect to have
- 1:31:44
- better more accurate and more productive understandings of these things sooner rather than later but as for right now
- 1:31:50
- as is so often the case in science especially biology it's less about getting clear-cut answers and more about
- 1:31:57
- asking bigger and better questions it's about recognizing the assumptions that we're making sometimes the ones we don't
- 1:32:03
- even realize that we're making and challenging them so that we can better understand nature in its own language
- 1:32:10
- that may sound daunting but handling concepts with no simple definitions or with context dependent definitions
- 1:32:16
- requires precisely the kind of special care and specific reasoning tools that as I mentioned earlier we're used to in
- 1:32:23
- biology turning old models on their heads and forcing us to dramatically change the way that we think about the
- 1:32:29
- entire world is the story of science it's what science is best at and in the
- 1:32:35
- meantime the least that we could do is try to tidy up our language if you've taken nothing else away from this
- 1:32:40
- conversation you should have at least picked up on the fact that even what you might call normal is a massively diverse
- 1:32:46
- group of people boiling concepts of manhood or Womanhood down to simple physical characteristics like a phus or
- 1:32:52
- a uterus or whatever chromosomes you like is not only unnecessarily reductive
- 1:32:57
- it's wholly inaccurate for example as we've already mentioned not every woman has a uterus and not everyone with a
- 1:33:04
- uterus is a woman whether you separate sex from gender or not we all live on a
- 1:33:09
- spectrum of sex and gender and you're not always going to have an easy time navigating it because people are under
- 1:33:15
- no obligation to make sense to you but none of the variation or fuzziness that I brought up so far means that we now
- 1:33:22
- have to say that chromosomes have nothing to do with sex at all or that there are 10,000 new Sexes and genders
- 1:33:28
- that need to be labeled or that there are no gendered patterns of behavior to speak of any more than a person
- 1:33:34
- occasionally being born without legs means that we can't call humans bipedal anymore it just means that we should try
- 1:33:40
- to be a little bit more specific most humans have two legs generally humans
- 1:33:46
- have two legs more often than not humans have two legs and similarly typically XY
- 1:33:53
- means male ordinarily males or boys on average boys
- 1:33:58
- like sports adding just a tiny bit of effort into your language choices makes what you're saying not only more
- 1:34:04
- inclusive but more scientifically accurate as well in fact you'll find that if you're being more scientifically
- 1:34:10
- accurate you are almost always being more inclusive too I understand that it's going to be a little uncomfortable
- 1:34:16
- to alter our conceptual Frameworks our heris sixs our language and our culture
- 1:34:21
- around a more detailed model of of sex and gender but hundreds of millions of
- 1:34:27
- people are counting on us to pull it together and figure it out so that they can go on living their lives in peace
- 1:34:33
- the way that we all want to and maybe you still don't believe me on this maybe you think that I'm just totally wrong or
- 1:34:39
- that I misread or misinterpreted something that's fine but there are two important things that I should point out
- 1:34:45
- first is that there's a lot more stuff that I could have put in here but I mainly specialize in evolution and human
- 1:34:50
- biology while I do have training in genetics and development I am neither a geneticist nor a
- 1:34:55
- developmental biologist so even if we had hit the limit of what I could have talked about here there still would have
- 1:35:01
- been a lot more information that could have been included and second is that I am not the only biologist that's coming
- 1:35:08
- to these conclusions as I mentioned earlier plenty of other scientists and scientific organizations are working on
- 1:35:14
- this new model and even Modern Biology textbooks are catching up the 10th edition of Campbell Biology Concepts and
- 1:35:21
- connections a super common textbook for inory biology courses for non- Majors published back in 2022 includes this
- 1:35:28
- paragraph on gender and sex the biochemical physiological and anatomical features associated with males and
- 1:35:35
- females are turning out to be more complex than previously realized with many genes involved in their development
- 1:35:42
- we now know that sex is not a binary state with just two defined outcomes
- 1:35:47
- because of the complexity of the genes and proteins involved in sex determination many variations exist some
- 1:35:54
- individuals are born with intermediate sexual or interex characteristics or even with anatomical features that do
- 1:36:01
- not match an individual's sense of their own gender known as transgender individuals sex determination is an
- 1:36:08
- active area of research that should yield a more sophisticated understanding in years to come it is literally basic
- References
- 1:36:15
- biology if you're interested in all this stuff and you'd like to know more or if you just want to fact check anything that I've said today I've left a link in
- 1:36:22
- the description with a detailed reference list of all the books papers and studies that I Ed to make this video
- 1:36:27
- including several things that I barely got to touch on and a few things that didn't even make it in for those of you
- 1:36:32
- who don't want to dig through all that and would rather just see what that reference section looks like here's a sneak peek
- 1:36:41
- [Music] [Applause] [Music]
- 1:37:21
- n n
- 1:37:47
- [Music]
- 1:37:53
- n [Music]
- 1:38:00
- [Applause] [Music]
- 1:38:39
- [Applause] so I guess just read through those and
- Conclusion
- 1:38:45
- get back to me we've covered a ton of stuff in this video but the one thing that I hope you learn more than anything
- 1:38:50
- else is that life is incredibly diverse and humans as living things are
- 1:38:56
- incredibly diverse as well we don't come in just one or two sizes shapes colors
- 1:39:02
- Styles Sexes or genders we are a product and a reflection of the multi-dimensional beauty that is life on
- 1:39:09
- this planet and we should respect and appreciate each other as such just as the rainforest teams with tens of
- 1:39:16
- thousands of species and the oceans Sparkle with vibrant colors of every Hue
- 1:39:22
- Humanity adorns the world with expressions of gender love and what it
- 1:39:27
- means to be alive our diversity highlights the beauty of Nature and the
- 1:39:33
- way we Embrace and celebrate that diversity highlights the beauty of our species the more we explore ourselves
- 1:39:40
- and each other the more we enrich our lives and societies as we learn more
- 1:39:46
- about the people around us we find meaning belonging and more than a little science along the way biology is just
- 1:39:54
- too big for binaries and if you asked me I wouldn't rather have it any other way and with that I'm Forest falky thank you
- 1:40:01
- so much for watching liking commenting subscribing and all the other stuff you do here on YouTube have an awesome rest
- 1:40:07
- of your day be yourself and never stop learning bye-bye
