* Welcome NFNC Friends!

It has been such a joy to share and connect with you during the
opportunities we've had at camp.  I would like:

- To have you know me better!
- To share some of my visionary projects with you!
- Maybe to be allies or project partners!

I invite you to explore the links in this document to learn about some
of the ways my heart and mind are engaged in visionary projects.

It's also totally okay if you're not interested in any of this!

/Please excuse the geeky format of this document,/
- /If you're curious about it, see *Geeky Details* below./

** Project #1: LOEL - The League of Extraordinary Learners

What if Learning was driven by and owned by curious Learners
- instead of "Educators"?

This is [[https://gregdavidson.github.io/loel/][The Vision of LOEL]]!

Many of my Favorite Books, Videos, etc.
- are on this this [[https://gregdavidson.github.io/loel/loel-media.html][LOEL Media Page]]

LOEL Curricula and More Resources:
- [[https://github.com/TouchPuuhonua/Deep-Rationality#readme][Deep Rationality]] :: A wonderful curriculum just starting!  You might
  like some of the resources here and perhaps you'd like to help this
  "curriculum" grow?
- [[https://github.com/GregDavidson/computing-magic#readme][Computing Magic]] :: Would you like to learn computing with the Magic
  Restored!  How to automate anything boring and aim for the stars?
- The [[https://github.com/GregDavidson/LOEL#readme][LOEL README]]!

** Two More Projects

- [[https://someclues.org][Some Clues for You!]]
- [[https://github.com/TouchPuuhonua/Nursery/tree/main/2025/sex-and-gender#readme][Touch & Otter Sex & Gender Resources]]

** I'd also like to share with you

- [[https://touchpuuhonua.github.io/][Touch Pu'uhonua's Ancient Home Page]]
- [[https://github.com/TouchPuuhonua][All Touch Pu'uhonua's GitHub Repositories]]
- [[https://github/com/GregDavidson][All GregDavidson's Repositories on GitHub]]

** Geeky Details

This document is written in [[https://orgmode.org][OrgMode]]. OrgMode is a Text Format Markup Language
with a lot of great advantages you can read about at that link.

This document is part of a [[https://en.wikipedia.org/wiki/Git][Git Repository]] which allows people to collaborate on
the development of any and all of the documents and other source files there.

A live copy of this repository is stored on [[https://github.com][GitHub]] to make it easier for
collaborators and other interested folks to find it.

If you might be interested in a special computing project aimed at
*Changing the World*
- ask me to explain the vision of [[https://gregdavidson.github.io/wicci-core-S0_lib/][The Wicci Project]]
