* Update on my Health for 2022

It's been some time since I wrote about my [[https://touchpuuhonua.github.io/2005/health][2005 Health Breakthrough]]
when I was 49.  Now I'm 63 and it's time for an update.

Seven years ago my wife died.  And this came less than four months
after we lost our beloved friend and partner Bill.  Now that I've had
some time to recover from the grief, it's time I write some updates to
my personal story.  I'll write about my wife elsewhere.  This update
is about my health.

Bill was an expert of dietary suppliments and also an extraordinary
cook, both of which skills he contributed to the health and well-being
of our family and many lucky friends.  After my wife died, I used a
dangerous but effective strategy to help manage my grief: I embraced
carbohydrates.

Some people thrive on carbohydrates.  I don't. Carbohydrates with a
high glycemic index cause me to put on weight, they diminish my energy
and mental focus.  But on the positive side, carbohydrates can help
take some of the edge off of anxiety and grief.  After my wife died, I
very deliberately indulged in carbohydrates, especially sweets,
including plenty of ice-cream.  It was an effective strategy.  It
helped me with my emotional pain.  I also gained about 20 kg, over 40
pounds, and lost much of my mental edge.  It was more than four years
until I felt ready to face my life without that crutch.

Without Bill's support, I couldn't face a sudden cutoff of
carbohydrates.  Instead I began to gradually taper off of them.  By
late last year I'd eliminated most fast carbohydrates from my diet and
I was within about 5 kg (about 15 pounds) of my weight target.  My
mental focus and endurance were improving.  I spent the first quarter
of this year at a retreat, teaching computational art.  I lost the
rest of the weight while I was there too, helped by the arduous
environmental conditions of wintering by California's Salton Sea!

This time I won't say that I've regained most of the health and vigor
of my 20's.  I have belly fat which stubbornly persists, wounding my
vanity.  I'm not as strong as I was.  I have regained much of my
cognitive capacities but not all I used to have, especially not mental
endurance: I seem to need significant recharge time after engaging in
work involving extended periods of intense mental focus.  I don't know
if the remaining disparity is because of my age, the damage of my
five-year carbohydrate binge or other factors.  The recovery I've
achieved is sufficient for my current needs and who knows: I may
recover further with time and good practice.  As long as I live long
enough, better interventions will become available to take me further.

My diet is decent but still not ideal.  My suppliment regime is
similar to what I was doing before and I'm experimenting with a few
new suppliments.  Other than the pregnenolone and time-release
vitamin-C though, it's all guesswork.  We simply don't have the
biomarkers which can guide us in optimizing our health practices.

I have, however, developed a totally awesome morning beverage which
consittutes my breakfast and keeps me going until mid-afternoon. I'll
share the recipe with you here:

#+begin_example
Prepare a cup of Green Tea
- I really like Stash Green Chai
Prepare a serving of espresso
- usually 1 shot (but sometimes 2) for me these days
In a blender, mix
- 1 cup (about 250g) 1% fat milk
- 1 scoop (about 23g) cacao powder
  - much nicer than the cocoa powder I used to use!
- 2 scoops (46g) protein powder
  - I use one scoop each of Orgain's chocolate and vanilla powders
  - excessively (for my palette) sweetened with stevia, but
  - the espresso, cacao and tea sufficiently cut the sweetness
- a couple squirts of MCT oil (I don't have an exact amount here)
- a generous shake of Pumpkin Pie Spice (mostly cinnamon and ginger)
  - I used to just use Saigon Cinnamon, which is also lovely
- a dash of L-Theonine [optional]
- the coffee and tea
Blend and serve!
#+end_example
